# Newer college real world LiDAR dataset
# General Params
verbosity: 2
input_point_cloud: true
use_lidar: &use_lidar true 
use_range_image: &use_range_image true
estimate_normal: &use_normal false
use_threadsafe_submap_collection: false
use_transform_caching: true
use_tf_transforms: true
transform_lookup_time: 0.05
global_frame_name: world
sensor_frame: os1_lidar
visualization_interval: -10.0
data_logging_interval: 0.0
print_timing_interval: -1.0
esdf_update_interval: 0.0 # 
max_input_queue_length: 1000
ros_spinning_threads: 8

lidar: # ouster-64 (change according to the intrinsic.yaml)
  verbosity: 1
  width: 1024 # Px
  height: 64
  fov_up: 16.6  # deg
  fov_down: -16.6
  max_range: &max_range 70.0  # m
  min_range: &min_range 1.0
  smooth_thre_ratio: 0.1 # normal estimation threshold

id_tracker:
  type: single_tsdf
  verbosity: 1
  
  use_lidar: *use_lidar
  use_range_image: *use_range_image
  use_class_layer: false
  use_instance_classification: false
  use_color: false
  integration_threads: 1 # slower, but can avoid SegFault

  # map allocator
  voxel_size: 0.2
  truncation_distance: -3
  voxels_per_side: 16

  # freespace esdf mapping
  esdf_integrator_name: voxfield # select from voxblox, voxfield, fiesta and edt
  esdf_fiesta_patch: true
  esdf_fiesta_break: false
  finer_esdf_on: false
  fixed_band_esdf_on: false
  occ_voxel_size_ratio: &occ_voxel_size_ratio 0.866
  fixed_band_ratio: 2.0
  esdf_max_distance_m: 6.0
  esdf_local_offset_x: 60
  esdf_local_offset_y: 60
  esdf_local_offset_z: 10

tsdf_integrator:  # different from those in voxblox
  # select from class_projective, class_raycast, class_adaptive, projective, raycast, adaptive, single_projective
  type: single_raycast
  verbosity: 2    

  use_range_image: *use_range_image
  use_lidar: *use_lidar   

  # Common
  apply_normal_refine_freespace: *use_normal # use Voxfield non-projective fusion on not
  behind_surface_reliable_band: true 
  reliable_band_ratio: 3.0
  reliable_normal_ratio_thre: 0.1
  use_weight_dropoff: true
  weight_dropoff_epsilon: -1.0 #if negative, means -k * voxel_size
  weight_reduction: true
  weight_reduction_exp: 2.0
  max_weight: 10000

  # Projective
  interpolation_method: adaptive  # nearest, bilinear, adaptive

  # Raycasting
  merged_raycasting: true # use "merged" raycast or not
  free_space_multi_threads: true # use multi-thread raycasting for the freespace submap independently
  freespace_carving_enabled: true # neccessary for dynamic mapping 
  max_ray_length_m: *max_range
  min_ray_length_m: *min_range
  

visualization:  
  submaps:
    type: single_tsdf  # submaps, single_tsdf
    verbosity: 1
    color_mode: normals # submaps, instances, color, normals, classes, change, classification (means the fusion confidence)
    visualization_mode: all  # all, active, active_only, inactive, persistent
    submap_color_discretization: 30 # be same as the image's
    visualize_mesh: true
    visualize_tsdf_blocks: true
    visualize_occ_voxels: false
    visualize_slice: true
    visualize_free_space_tsdf: true
    visualize_free_space_esdf: true
    visualize_free_space_gsdf: true
    visualize_ground_tsdf: false
    visualize_bounding_volumes: true
    include_free_space: true
    slice_height: 1.0
    occ_voxel_size_ratio: *occ_voxel_size_ratio
  
  planning:
    verbosity: 1
    visualize_slice: true
    slice_resolution: 0.2
    slice_height: 0.0
  
  tracking:
    verbosity: 1
    visualize_tracking: true

# Available services:
# rosservice call /panoptic_mapper/save_map "file_path: '/path/to/xxx.panmap'"
# rosservice call /panoptic_mapper/save_esdf_map "file_path: '/path/to/xxx..esdf'" 
# rosservice call /panoptic_mapper/save_mesh "file_path: '/path/to/xxx'" # get ply
# rosservice call /panoptic_mapper/set_visualization_mode "color_mode: 'color'"
# rosservice call /panoptic_mapper/set_visualization_mode "visualization_mode: 'active'"

