# BUP RGBD dataset
# General Params
verbosity: 4
output_on: false
output_base_path: /media/yuepan/DATA/1_data/CKA/results/20220919_row6/cam2_run_show
shutdown_when_finished: false
save_map_path_when_finished: /media/yuepan/DATA/1_data/CKA/results/20220919_row6/cam2_run_show
input_point_cloud: false
use_lidar: &use_lidar false 
use_range_image: &use_range_image true
filter_depth_image: true
filter_depth_erosion_size: 3 # 5
estimate_normal: &use_normal false
use_threadsafe_submap_collection: false
use_transform_caching: true
use_tf_transforms: true # here only works for the model mesh, if range image is used, then tf is the only option
use_transform_msg: false # use "transform" or "pose" rosmsg
transform_lookup_time: 0.2
global_frame_name: odom
robot_frame_name: camera2_color_optical_frame
sensor_frame_name: camera2_color_optical_frame 
robot_mesh_interval: -1.0
robot_mesh_scale: 3.5
visualization_interval: -2.0
data_logging_interval: 0.0
print_timing_interval: -1.0
esdf_update_interval: 0.0
max_input_queue_length: 1000
ros_spinning_threads: 12
msg_latency_s: 0.25

# Use CSV label handler
labels:
  type: csv
  file_name: /media/yuepan/DATA/1_data/CKA/CKA_sweet_pepper/BUP20/CKA_sweet_pepper_2020_summer/cka_bup_labels.csv

camera:
  verbosity: 1
  width: 1280 # Px
  height: 720
  vx: 643.212158203125
  vy: 361.7205505371094
  fx: 920.6524047851562
  fy: 919.456298828125
  depth_unit: 1000.
  max_range: &max_range 1.3  # m
  min_range: &min_range 0.5
  smooth_thre_ratio: 0.1 

  # camera 1 (color and depth): 916.4022216796875, 0.0, 659.4613647460938, 0.0, 916.4210205078125, 374.5310974121094, 0.0, 0.0, 1.0
  # camera 2 (color and depth): 920.6524047851562, 0.0, 643.212158203125, 0.0, 919.456298828125, 361.7205505371094, 0.0, 0.0, 1.0 
  # camera 3 (color and depth): 916.903076171875,  0.0, 637.0918579101562, 0.0, 915.8038330078125, 359.5274963378906, 0.0, 0.0, 1.0
  
submap_allocator:
  type: semantic  # semantic
  verbosity: 1
  
  # submaps
  voxels_per_side: &voxels_per_side 8 # originally 16
  truncation_distance: -2 # negative = #vs (scale)

  mesh: # It's better to use false and 1 as a good combination here, and set foreign_rays_clear = true
    clear_foreign_voxels: false # if true: close the mesh of each submap by assign the foreign voxel corners the truncated distance
    required_belonging_corners: 1 # A voxel is be regarded as valid only when $required_belonging_corners of 8 corners are belonging to the submap's id
  
  classification:
    type: moving_binary_count
  
  # Semantic
  small_instance_voxel_size: 0.003 # sweet pepper # 0.005
  medium_instance_voxel_size: 0.01
  large_instance_voxel_size: 0.01
  background_voxel_size: 0.01 # backgrounds # 0.01
  unknown_voxel_size: 0.02
  
freespace_allocator:
  type: monolithic  # monolithic
  verbosity: 1  
  voxels_per_side: *voxels_per_side 
  truncation_distance: -3   
  voxel_size: 0.05

  # freespace esdf mapping
  esdf_integrator_name: voxfield # select from voxblox, voxfield, fiesta and edt
  esdf_fiesta_patch: true
  esdf_fiesta_break: false
  finer_esdf_on: false
  esdf_max_distance_m: 2.5
  esdf_local_offset_x: 30
  esdf_local_offset_y: 30
  esdf_local_offset_z: 10

id_tracker:
  type: projective # select from ground_truth, projective, detectron, single_tsdf
  verbosity: 1

  rotate_image: true

  use_lidar: *use_lidar  
  
  # Projective ID tracker
  # rendering_threads: 1
  rendering_subsampling: 2 # try to speed up with multi-thread
  depth_tolerance: -3  # m, negative = #vs, -5, 0.05
  tracking_metric: IoU  # IoU, overlap
  match_acceptance_threshold: 0.15  
  min_allocation_size: 400 # px, for new submap allocation.
  use_class_data_for_matching: true  
  use_approximate_rendering: false # only use the vertex points
  vis_render_image: false

tsdf_integrator:  # different from those in voxblox
  # select from class_projective, class_raycast, class_adaptive, projective, raycast, adaptive, single_projective， single_raycast
  type: class_raycast 
  verbosity: 2    

  use_lidar: *use_lidar   

  # Common
  skip_free_space_submap: true # if true, only do panoptic 3d reconstruction
  curve_assumption: true
  behind_surface_reliable_band: true
  apply_normal_refine: *use_normal               # use Voxfield non-projective fusion or not (for each submap)
  apply_normal_refine_freespace: *use_normal     # use Voxfield non-projective fusion or not
  reliable_band_ratio: 2.0
  reliable_normal_ratio_thre: 0.2
  use_weight_dropoff: false
  weight_dropoff_epsilon: -1.0  # if negative, means -k * voxel_size
  weight_reduction: true
  weight_reduction_exp: 2.0 # for rgbd image
  max_weight: 10000
  
  # Projective Integrator
  # Now the allocation is quite time consuming
  interpolation_method: adaptive  # nearest, bilinear, adaptive
  allocate_neighboring_blocks: false # use false if you'd like to save time
  foreign_rays_clear: false # only works for projective integrator, if false, then we do not allow a multi-class submap (projected pixel does not belongs to the current submap)

  # Raycast Integrator
  merged_raycasting: true # use "merged" raycast or not
  only_merge_freespace: false # if "merged" raycast is select, only apply it to the free-space submap
  free_space_multi_threads: true # use multi-thread raycasting for the freespace submap independently
  voxel_carving_enabled: false # space carving for submaps 
  freespace_carving_enabled: true
  max_ray_length_m: *max_range # this is not for esdf
  min_ray_length_m: *min_range
  image_pix_down_rate: 2 # downsampling rate from the pixels to the point cloud
  
  
  # Class Projective
  use_binary_classification: true
  use_instance_classification: &use_instance_classification false
  update_only_tracked_submaps: true 
  
map_management:
  type: submaps
  verbosity: 4
  
  # Frequencies
  prune_active_blocks_frequency: 5 # 5
  activity_management_frequency: 1 # 1
  change_detection_frequency: 0
  
  # Behavior
  # If find candidate inactive submaps which have the bounding volume intersection and similar TSDF as the currently deactivated one, merge them or not
  merge_deactivated_submaps_if_possible: &merge_map false
  # When deactivate the submap, removes those non-belonging points from the TSDF and deletes the class layer or not
  apply_class_layer_when_deactivating_submaps: false
  
  activity_manager:
    verbosity: 4
    required_reobservations: 3 # Consecutive observations to keep new submaps.
    deactivate_after_missed_detections: 10  # Deactivate submaps when not observed for x frames.
    update_after_deactivation: *merge_map
  # Done by activity manager
  # 1. checkRequiredRedetection, if the submap is not tracked consecutive for X frames from the beginning, discard the submap
  # 2. checkMissedDetections, if the submap is not not detected for Y consecutive frames, deactivate the submap, but it should also obey 1
  # 3. mergeSubmapIfPossible, when one submap is deactivated, try to find another inactive submap for merging. If the merging condition is fulfilled, merge them and keep the older submap 
  
  tsdf_registrator:
    verbosity: 3
    min_voxel_weight: 0.00001
    error_threshold: -2 # m, negative = #vs
    match_rejection_points: 20  
    match_rejection_percentage: 0.02
    match_acceptance_points: 20
    match_acceptance_percentage: 0.02
    normalize_by_voxel_weight: true
    
  layer_manipulator:
      verbosity: 3
      use_instance_classification: *use_instance_classification
  
visualization:  
  submaps:
    type: submaps  # submaps, single_tsdf
    verbosity: 1
    color_mode: submaps # submaps, instances, color, normals, classes, change, classification
    visualization_mode: all  # all, active, active_only, inactive, persistent
    submap_color_discretization: 30
    visualize_mesh: true
    visualize_tsdf_blocks: true
    visualize_occ_voxels: true
    visualize_slice: true
    visualize_free_space_tsdf: true
    visualize_free_space_esdf: true
    visualize_free_space_gsdf: true
    visualize_bounding_volumes: true
    include_free_space: false
    mesh_min_weight: 0.000001
    slice_height: 0.0
  
  planning:
    verbosity: 1
    visualize_slice: true
    slice_resolution: 0.1
    slice_height: -0.5
  
  tracking:
    verbosity: 1
    visualize_tracking: true

# Available services:
# rosservice call /panoptic_mapper/save_map "file_path: '/path/to/xxx.panmap'"
# rosservice call /panoptic_mapper/save_esdf_map "file_path: '/path/to/xxx..esdf'" 

# rosservice call /panoptic_mapper/save_mesh "file_path: '/path/to/xxx'" # get ply of each submap in a folder
# rosservice call /panoptic_mapper/set_visualization_mode "color_mode: 'color'"
# rosservice call /panoptic_mapper/set_visualization_mode "color_mode: 'submaps'"
# rosservice call /panoptic_mapper/set_visualization_mode "visualization_mode: 'active'"
# rosservice call /panoptic_mapper/set_visualization_mode "visualization_mode: 'all'"