# B: robot body frame, C: camera frame
# a dirty fix
T_B_C: # here actually only for the model
- [ 0.0, 0.0, 1.0, 0.0]
- [ 0.0, 1.0, 0.0, 0.0]
- [ -1.0, 0.0, 0.0, 0.0]
- [ 0.0, 0.0, 0.0, 1.0]

invert_T_B_C: false

# actually T_V_C (C = cam0, V = vicon)
T_B_D:
- [ 1.0, 0.0, 0.0, 0.0]
- [ 0.0, 1.0, 0.0, 0.0]
- [ 0.0, 0.0, 1.0, 0.0]
- [ 0.0, 0.0, 0.0, 1.0]
invert_T_B_D: false